object AboutBox: TAboutBox
  Left = 124
  Top = 622
  BorderStyle = bsDialog
  Caption = 'AboutBox'
  ClientHeight = 269
  ClientWidth = 335
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'MS Sans Serif'
  Font.Style = []
  OldCreateOrder = True
  Position = poScreenCenter
  PixelsPerInch = 96
  TextHeight = 13
  object Label1: TLabel
    Left = 40
    Top = 32
    Width = 212
    Height = 29
    Caption = 'CD-Verwaltung 1.0'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clBlack
    Font.Height = -24
    Font.Name = 'Arial'
    Font.Style = [fsBold]
    ParentFont = False
  end
  object Label2: TLabel
    Left = 88
    Top = 80
    Width = 24
    Height = 13
    Caption = '1996'
  end
  object Label3: TLabel
    Left = 216
    Top = 160
    Width = 93
    Height = 13
    Caption = 'D-86938-Schondorf'
  end
  object Label4: TLabel
    Left = 160
    Top = 104
    Width = 97
    Height = 13
    Caption = 'von Thomas Pflügler'
  end
  object Label5: TLabel
    Left = 72
    Top = 136
    Width = 65
    Height = 13
    Caption = 'Uttinger Str. 2'
  end
  object BitBtn1: TBitBtn
    Left = 136
    Top = 224
    Width = 75
    Height = 25
    TabOrder = 0
    Kind = bkOK
  end
end
